"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  pt: {
    // Página Inicial
    loading: "A carregar...",
    header_title: "Outlook Kanban",
    hero_title_1: "Os seus e-mails,",
    hero_title_2: "organizados no quadro.",
    hero_subtitle: "Uma interface visual ligada diretamente ao seu Outlook. Ideal para estudantes e profissionais que precisam de gerir mensagens como tarefas reais.",
    feature_1: "Colunas personalizadas para organization rápida.",
    feature_2: "Função Snooze para adiar conversas para mais tarde.",
    feature_3: "Privacidade total: não guardamos os seus e-mails.",
    login_ms: "Entrar com a Microsoft",
    drag_here: "Arraste para aqui",
    footer_desc: "Projeto de Gestão de E-mails.",
    terms: "Termos e Condições",
    privacy: "Privacidade",
    close: "Fechar",
    modal_terms_title: "Termos de Uso",
    modal_privacy_title: "Como gerimos os seus dados",
    terms_1_title: "1. Sobre o Projeto",
    terms_1_desc: "O Gestor Kanban é uma ferramenta desenvolvida em contexto académico.",
    terms_2_title: "2. Permissões da Microsoft",
    terms_2_desc: "Para funcionar, a aplicação pede permissão para ler, modificar e enviar e-mails em seu nome através da API oficial da Microsoft Graph. O login é gerido pela Microsoft, nós nunca vemos a sua password.",
    terms_3_title: "3. Responsabilidade",
    terms_3_desc: "Mover ou eliminar e-mails no Kanban afeta a sua conta Outlook real. O utilizador é responsável pelas ações realizadas através desta interface.",
    privacy_1_title: "1. Nós não lemos os seus e-mails",
    privacy_1_desc_1: "A arquitetura desta aplicação foi pensada para a privacidade. ",
    privacy_1_bold: "O corpo dos seus e-mails, os remetentes e os anexos nunca são guardados na nossa base de dados.",
    privacy_1_desc_2: " Eles vão diretamente da Microsoft para o seu ecrã.",
    privacy_2_title: "2. O que fica guardado no nosso servidor?",
    privacy_2_desc: "Apenas \"etiquetas\" (metadados). Guardamos o ID técnico do e-mail, em que coluna do Kanban o colocou, as tags criadas e as configurações de Snooze.",
    privacy_3_title: "3. Controlo Total",
    privacy_3_desc: "Pode revogar o acesso da aplicação a qualquer momento nas definições de segurança da sua conta da Microsoft.",

    // Sidebar / Dashboard Layout
    app_title: "Gestor de Emails",
    app_subtitle: "Kanban Dashboard",
    expand_menu: "Expandir menu",
    collapse_menu: "Recolher menu",
    new_email: "Novo E-mail",
    menu_inbox_group: "Caixa de Entrada",
    menu_kanban: "O meu Kanban",
    menu_sent: "Enviados",
    menu_snoozed: "Adiados (Snooze)",
    menu_archived: "Arquivados",
    menu_spam: "Spam",
    menu_deleted: "Eliminados",
    menu_columns_group: "As Minhas Colunas",
    col_inbox: "Caixa de Entrada",
    manage_columns: "Gerir Colunas",
    menu_tools_group: "Ferramentas",
    show_filters: "Mostrar Filtros",
    hide_filters: "Ocultar Filtros",
    open_settings: "Abrir Definições",
    user_default: "Utilizador",
    settings: "Definições",
    logout: "Terminar Sessão",

    // Kanban Board Views
    supabase_error: "Supabase não configurado.",
    emails_count: "emails",
    conversations_count: "conversas",
    col_unknown: "Coluna Desconhecida",
    empty_col: "Nenhum e-mail nesta lista. Tudo limpo!",
    empty_snoozed: "Nenhum e-mail adiado.",
    empty_archived: "Nenhum e-mail no arquivo do Outlook.",
    empty_sent: "Ainda não enviou nenhuma mensagem.",
    empty_deleted: "O lixo está limpo.",
    empty_spam: "Não tem mensagens de spam.",
    view_construction_1: "Vista",
    view_construction_2: "em construção...",
    title_snoozed: "Adiados (Snooze)",
    title_archived: "Arquivo",
    title_sent: "Enviados",
    title_deleted: "Eliminados",
    title_spam: "Lixo Eletrónico",

    // Definições
    settings_title: "Definições Gerais",
    settings_theme: "Tema do Painel",
    settings_language: "Idioma da Plataforma",
    bg_slate: "Padrão",
    bg_blue: "Azul Noite",
    bg_mountains: "Montanhas",
    bg_ocean: "Oceano",
    bg_forest: "Floresta",

    // Gestor de Colunas 
    color_blue: "Azul",
    color_green: "Verde",
    color_yellow: "Amarelo",
    color_red: "Vermelho",
    color_purple: "Roxo",
    color_orange: "Laranja",
    color_pink: "Rosa",
    color_gray: "Cinza",
    custom_badge: "Personalizada",
    system_badge: "Sistema",
    error_title: "Erro",
    error_reorder: "Não foi possível guardar a nova ordem.",
    toast_col_created: "Coluna criada",
    toast_col_created_desc: "A coluna '{name}' foi criada com sucesso.",
    error_create_col: "Não foi possível criar a coluna.",
    toast_col_updated: "Coluna atualizada",
    toast_col_updated_desc: "A coluna '{name}' foi atualizada com sucesso.",
    error_update_col: "Não foi possível atualizar a coluna.",
    toast_col_deleted: "Coluna excluída",
    toast_col_deleted_desc: "A coluna '{name}' foi excluída e os emails foram movidos para a Caixa de Entrada.",
    error_delete_col: "Não foi possível excluir a coluna.",
    kanban_org_title: "Organização do Kanban",
    your_structure: "A sua Estrutura",
    new_col_btn: "Nova Coluna",
    inbox_desc: "Coluna principal de receção (fixa)",
    empty_kanban: "O seu Kanban está vazio.",
    empty_kanban_desc: "Crie colunas para organizar o seu fluxo de trabalho.",
    create_col_title: "Criar Nova Coluna",
    col_name_label: "Nome da Coluna",
    col_name_placeholder: "Ex: Em Revisão, Urgente, Feito...",
    visual_id_label: "Identidade Visual",
    icon_label: "Ícone Representativo",
    cancel_btn: "Cancelar",
    save_btn: "Guardar",
    edit_col_title: "Editar Coluna",
    save_changes_btn: "Salvar Alterações",
    delete_col_title: "Eliminar Coluna",
    delete_col_confirm: "Tem a certeza que deseja eliminar a coluna",
    delete_col_warn: "Os e-mails não serão perdidos. Qualquer e-mail que esteja nesta coluna voltará imediatamente para a sua",

    // Cartão de Email
    no_subject: "(Sem assunto)",
    to_prefix: "Para:",
    from_prefix: "De:",
    email_settings: "Configurações do Email",
    priority_label: "Prioridade",
    priority_low: "Baixa",
    priority_medium: "Média",
    priority_high: "Alta",
    priority_urgent: "Urgente",
    tags_label: "Tags",
    new_tag_placeholder: "Nova tag",
    add_btn: "Adicionar",
    badge_new: "Novo",
    badge_sent: "Enviado",

    // Compositor de Emails
    loading_contacts: "A carregar contactos...",
    no_contacts: "Nenhum contacto encontrado.",
    undo_seconds_1: "Tem",
    undo_seconds_2: "segundo",
    undo_seconds_3: "segundos",
    undo_seconds_4: "para anular o envio.",
    send_msg: "Enviar Mensagem",
    forward: "Reencaminhar",
    reply: "Responder",
    reply_all: "Responder a Todos",
    new_msg: "Nova Mensagem",
    sig_saved: "Assinatura Guardada",
    sig_saved_desc: "A assinatura '{name}' está pronta a usar.",
    sig_deleted: "Assinatura Removida",
    sig_deleted_desc: "A assinatura foi eliminada com sucesso.",
    sending_msg: "A enviar mensagem...",
    undo_send: "Anular envio",
    undo_btn: "Anular",
    send_undone: "Envio Anulado",
    send_undone_desc: "O e-mail foi cancelado e não foi enviado.",
    send_success: "Email enviado com sucesso!",
    send_success_desc: "A sua mensagem foi entregue e organizada.",
    send_error: "Erro ao enviar email",
    unexpected_error: "Ocorreu um erro inesperado.",
    to_label: "Para",
    cc_bcc_btn: "CC / CCO",
    cc_label: "Cc",
    bcc_label: "Cco",
    importance_label: "Grau",
    importance_low: "Baixa Importância",
    importance_normal: "Normal",
    importance_high: "Alta Importância",
    subject_label: "Tema",
    subject_placeholder: "Assunto da mensagem",
    font_placeholder: "Fonte",
    size_placeholder: "Tam.",
    text_color: "Cor do Texto",
    highlight_color: "Cor de Destaque",
    body_placeholder: "Escreva a sua mensagem aqui...",
    attach_btn: "Anexar",
    sig_btn: "Assinatura",
    no_sig: "Nenhuma assinatura",
    manage_sigs_btn: "+ Gerir Assinaturas",
    only_reply: "Apenas Responder",
    only_forward: "Apenas Reencaminhar",
    send_archive: "Enviar e Arquivar",
    send_snooze: "Enviar e Adiar (Amanhã)",
    send_move_to: "Enviar e Mover para...",
    send_to_col: "Enviar para",
    manage_sigs_title: "Gerir Assinaturas",
    saved_sigs: "Assinaturas Guardadas",
    create_sig: "Criar Nova Assinatura",
    sig_name_placeholder: "Nome (ex: IPVC, Pessoal, Inglês...)",
    add_image: "Adicionar Imagem",
    sig_body_placeholder: "Escreva a sua assinatura aqui...",
    save_sig_btn: "Guardar Assinatura",
    history_from: "De:",
    history_sent: "Enviado:",
    history_to: "Para:",
    history_cc: "Cc:",
    history_subject: "Assunto:",

    // Painel de Filtros
    filter_show: "Mostrar Filtros",
    filter_active_single: "ativo",
    filter_active_plural: "ativos",
    filter_title: "Filtros de Pesquisa",
    filter_clear: "Limpar Tudo",
    filter_search_label: "Busca Geral",
    filter_search_placeholder: "Ex: fatura, relatório, assunto...",
    filter_sender_label: "Remetente",
    filter_sender_placeholder: "email@exemplo.com ou Nome",
    filter_tags_label: "Tags",
    filter_tags_placeholder: "Escreva e prima Enter...",
    filter_tags_suggestions: "Sugestões rápidas",
    filter_priority_label: "Prioridade",
    filter_priority_low: "Baixa",
    filter_priority_medium: "Média",
    filter_priority_high: "Alta",
    filter_priority_urgent: "Urgente",
    filter_attachments_label: "Anexos",
    filter_att_all: "Todos os emails",
    filter_att_yes: "Apenas com anexos",
    filter_att_no: "Sem anexos",
    filter_read_label: "Estado de Leitura",
    filter_read_all: "Lidos e Não Lidos",
    filter_read_yes: "Apenas Lidos",
    filter_read_no: "Apenas Não Lidos",
    filter_date_label: "Período",
    filter_date_to: "a",

    // Colunas Kanban (Grupos de Data e UI)
    group_today: "Hoje",
    group_yesterday: "Ontem",
    group_last_week: "Última Semana",
    group_last_month: "Último Mês",
    group_older: "Mais Antigos",
    snoozed_single: "Adiado",
    snoozed_plural: "Adiados",
    col_all_clear: "Tudo em dia!",
    loading_more: "A carregar...",
    search_older: "Procurar mais antigos",
    searching: "A procurar...",
    unread_emails: "por ler",

    // Cartão de Thread Kanban
    priority_none: "Nenhuma Prioridade",
    priority_low_text: "Baixa",
    priority_medium_text: "Média",
    priority_high_text: "Alta",
    priority_urgent_text: "Urgente",
    snooze_title: "Adiar E-mail (Snooze)",
    snooze_later_today: "Mais logo (Daqui a 4h)",
    snooze_tomorrow: "Amanhã de Manhã",
    snooze_next_week: "Próxima Semana",
    snooze_custom_date: "Escolher Data Específica",
    snooze_confirm: "Confirmar",
    snoozed_success: "E-mail Adiado (Snooze)",
    snoozed_desc: "A mensagem reaparecerá no dia",
    snooze_wake: "Despertar Agora",
    snooze_cancelled: "Snooze Cancelado",
    snooze_cancelled_desc: "O e-mail voltou a estar ativo no Kanban.",
    snooze_wakes_at: "Acorda a:",
    archive_success: "Conversa Arquivada",
    archive_desc: "Movida para a pasta de Arquivo do Outlook.",
    archive_error: "Falha ao arquivar e-mail",
    restore_inbox: "Mover para Caixa de Entrada",
    restore_not_spam: "Não é Spam",
    restore_success: "Restaurado",
    restore_desc: "Conversa movida para a Caixa de Entrada.",
    restore_error: "Falha ao restaurar e-mail",
    spam_success: "Spam",
    spam_desc: "Conversa movida para Lixo Eletrónico.",
    spam_error: "Falha ao marcar como Spam",
    spam_mark: "Marcar como Spam",
    delete_forever: "Eliminar para Sempre",
    delete_normal: "Eliminar",
    delete_success_forever: "Eliminado Definitivamente",
    delete_desc_forever: "A conversa foi removida permanentemente.",
    delete_success: "Eliminado",
    delete_desc: "Conversa movida para os Itens Eliminados.",
    delete_error_forever: "Falha ao eliminar definitivamente",
    delete_error: "Falha ao eliminar e-mail",
    delete_modal_title: "Eliminar E-mail",
    delete_modal_desc_forever: "Esta ação irá apagar a conversa permanentemente. Não poderá ser recuperada.",
    delete_modal_desc: "Tem a certeza de que pretende eliminar esta conversa? Esta ação moverá os e-mails para a pasta de Itens Eliminados.",
    manage_tags_deadlines: "Gerir Prazos e Tags",
    archive_btn: "Arquivar",
    due_date_label: "Data Limite (Prazo)",
    add_tags_label: "Adicionar Tags",
    tag_placeholder: "Nova tag",
    you_sender: "Você",
    msg_count: "msg",
    unread_badge: "por ler",

    // Visualizador de Email (Email Viewer)
    error_load_email: "Não foi possível carregar o conteúdo completo do email.",
    email_read: "Email lido",
    email_read_desc: "Marcado como lido com sucesso.",
    email_archived: "Email arquivado",
    email_archived_desc: "A mensagem foi movida para o arquivo.",
    error_archive: "Não foi possível arquivar o email.",
    email_deleted: "Email eliminado",
    email_deleted_desc: "A mensagem foi movida para os Itens Eliminados.",
    error_delete: "Não foi possível eliminar o email.",
    error_attachment: "Erro ao processar anexo",
    error_attachment_desc: "Não foi possível ler este ficheiro.",
    error_download: "Erro de Download",
    error_download_desc: "O conteúdo deste anexo não está disponível.",
    tasks_btn: "Tarefas",
    to_label_caps: "PARA:",
    new_msg_badge: "Nova Mensagem",
    attachments_title: "Anexos",
    open_attachment: "Abrir anexo",
    download_attachment: "Descarregar anexo",
    loading_content: "A carregar conteúdo...",
    reply_btn: "Responder",
    reply_all_btn: "Todos",
    forward_btn: "Encaminhar",
    task_list: "Lista de Tarefas",
    progress: "Progresso",
    of_word: "de",
    no_tasks: "Nenhuma tarefa associada.",
    click_to_add: "Clique abaixo para adicionar.",
    task_placeholder: "Descreva a tarefa...",
    new_task: "Nova Tarefa",
    delete_email_desc: "Tem a certeza de que pretende eliminar esta mensagem? Esta ação moverá o e-mail para a pasta de Itens Eliminados.",
    content_unavailable: "Conteúdo não disponível",
    delete_btn: "Eliminar",
    close_btn: "Fechar",
    delete_email_title: "Eliminar E-mail",

    // Backoffice / Admin
    checking_creds: "A verificar credenciais...",
    restricted_area: "Área Reservada",
    admin_only: "Apenas administradores podem aceder a esta página.",
    back_to_platform: "Voltar à Plataforma",
    admin_panel_title: "Painel de Administração",
    admin_panel_desc: "Monitorização e métricas da plataforma Kanban.",
    exit_btn: "Sair",
    total_users: "Total Utilizadores",
    active_7_days: "Ativos (7 Dias)",
    registered_users: "Utilizadores Registados",
    search_user_placeholder: "Procurar utilizador...",
    table_account: "Conta & E-mail",
    table_joined: "Adesão",
    table_last_active: "Última Atividade",
    loading_info: "A carregar informações...",
    no_user_found: "Nenhum utilizador encontrado.",
    online_now: "Online Agora",
    offline: "Offline",
  },


  en: {
    // Página Inicial
    loading: "Loading...",
    header_title: "Outlook Kanban",
    hero_title_1: "Your emails,",
    hero_title_2: "organized on the board.",
    hero_subtitle: "A visual interface connected directly to your Outlook. Ideal for students and professionals who need to manage messages like real tasks.",
    feature_1: "Custom columns for quick organization.",
    feature_2: "Snooze function to defer conversations for later.",
    feature_3: "Total privacy: we don't store your emails.",
    login_ms: "Sign in with Microsoft",
    drag_here: "Drag here",
    footer_desc: "Email Management Project.",
    terms: "Terms and Conditions",
    privacy: "Privacy",
    close: "Close",
    modal_terms_title: "Terms of Use",
    modal_privacy_title: "How we manage your data",
    terms_1_title: "1. About the Project",
    terms_1_desc: "The Kanban Manager is a tool developed in an academic context.",
    terms_2_title: "2. Microsoft Permissions",
    terms_2_desc: "To function, the application requests permission to read, modify, and send emails on your behalf through the official Microsoft Graph API. Login is managed by Microsoft; we never see your password.",
    terms_3_title: "3. Responsibility",
    terms_3_desc: "Moving or deleting emails in Kanban affects your real Outlook account. The user is responsible for the actions performed through this interface.",
    privacy_1_title: "1. We do not read your emails",
    privacy_1_desc_1: "The architecture of this application was designed for privacy. ",
    privacy_1_bold: "The body of your emails, senders, and attachments are never stored in our database.",
    privacy_1_desc_2: " They go straight from Microsoft to your screen.",
    privacy_2_title: "2. What is stored on our server?",
    privacy_2_desc: "Only \"tags\" (metadata). We store the technical ID of the email, which Kanban column you placed it in, the created tags, and Snooze settings.",
    privacy_3_title: "3. Total Control",
    privacy_3_desc: "You can revoke the application's access at any time in the security settings of your Microsoft account.",

    // Sidebar / Dashboard Layout
    app_title: "Email Manager",
    app_subtitle: "Kanban Dashboard",
    expand_menu: "Expand menu",
    collapse_menu: "Collapse menu",
    new_email: "New Email",
    menu_inbox_group: "Inbox",
    menu_kanban: "My Kanban",
    menu_sent: "Sent Items",
    menu_snoozed: "Snoozed",
    menu_archived: "Archive",
    menu_spam: "Junk Email",
    menu_deleted: "Deleted Items",
    menu_columns_group: "My Columns",
    col_inbox: "Inbox",
    manage_columns: "Manage Columns",
    menu_tools_group: "Tools",
    show_filters: "Show Filters",
    hide_filters: "Hide Filters",
    open_settings: "Open Settings",
    user_default: "User",
    settings: "Settings",
    logout: "Sign Out",

    // Kanban Board Views
    supabase_error: "Supabase not configured.",
    emails_count: "emails",
    conversations_count: "conversations",
    col_unknown: "Unknown Column",
    empty_col: "No emails in this list. All clear!",
    empty_snoozed: "No snoozed emails.",
    empty_archived: "No emails in the Outlook archive.",
    empty_sent: "You haven't sent any messages yet.",
    empty_deleted: "Trash is empty.",
    empty_spam: "No spam messages.",
    view_construction_1: "View",
    view_construction_2: "under construction...",
    title_snoozed: "Snoozed",
    title_archived: "Archive",
    title_sent: "Sent Items",
    title_deleted: "Deleted Items",
    title_spam: "Junk Email",

    // Definições
    settings_title: "General Settings",
    settings_theme: "Dashboard Theme",
    settings_language: "Platform Language",
    bg_slate: "Default",
    bg_blue: "Night Blue",
    bg_mountains: "Mountains",
    bg_ocean: "Ocean",
    bg_forest: "Forest",

    // Gestor de Colunas 
    color_blue: "Blue",
    color_green: "Green",
    color_yellow: "Yellow",
    color_red: "Red",
    color_purple: "Purple",
    color_orange: "Orange",
    color_pink: "Pink",
    color_gray: "Gray",
    custom_badge: "Custom",
    system_badge: "System",
    error_title: "Error",
    error_reorder: "Could not save the new order.",
    toast_col_created: "Column created",
    toast_col_created_desc: "Column '{name}' was created successfully.",
    error_create_col: "Could not create the column.",
    toast_col_updated: "Column updated",
    toast_col_updated_desc: "Column '{name}' was updated successfully.",
    error_update_col: "Could not update the column.",
    toast_col_deleted: "Column deleted",
    toast_col_deleted_desc: "Column '{name}' was deleted and emails were moved to Inbox.",
    error_delete_col: "Could not delete the column.",
    kanban_org_title: "Kanban Organization",
    your_structure: "Your Structure",
    new_col_btn: "New Column",
    inbox_desc: "Main reception column (fixed)",
    empty_kanban: "Your Kanban is empty.",
    empty_kanban_desc: "Create columns to organize your workflow.",
    create_col_title: "Create New Column",
    col_name_label: "Column Name",
    col_name_placeholder: "Ex: In Review, Urgent, Done...",
    visual_id_label: "Visual Identity",
    icon_label: "Representative Icon",
    cancel_btn: "Cancel",
    save_btn: "Save",
    edit_col_title: "Edit Column",
    save_changes_btn: "Save Changes",
    delete_col_title: "Delete Column",
    delete_col_confirm: "Are you sure you want to delete the column",
    delete_col_warn: "Emails will not be lost. Any email in this column will immediately return to your",

    // Cartão de Email
    no_subject: "(No subject)",
    to_prefix: "To:",
    from_prefix: "From:",
    email_settings: "Email Settings",
    priority_label: "Priority",
    priority_low: "Low",
    priority_medium: "Medium",
    priority_high: "High",
    priority_urgent: "Urgent",
    tags_label: "Tags",
    new_tag_placeholder: "New tag",
    add_btn: "Add",
    badge_new: "New",
    badge_sent: "Sent",

    // Compositor de Emails
    loading_contacts: "Loading contacts...",
    no_contacts: "No contacts found.",
    undo_seconds_1: "You have",
    undo_seconds_2: "second",
    undo_seconds_3: "seconds",
    undo_seconds_4: "to undo the send.",
    send_msg: "Send Message",
    forward: "Forward",
    reply: "Reply",
    reply_all: "Reply to All",
    new_msg: "New Message",
    sig_saved: "Signature Saved",
    sig_saved_desc: "The signature '{name}' is ready to use.",
    sig_deleted: "Signature Removed",
    sig_deleted_desc: "The signature was deleted successfully.",
    sending_msg: "Sending message...",
    undo_send: "Undo send",
    undo_btn: "Undo",
    send_undone: "Send Undone",
    send_undone_desc: "The email was cancelled and not sent.",
    send_success: "Email sent successfully!",
    send_success_desc: "Your message was delivered and organized.",
    send_error: "Error sending email",
    unexpected_error: "An unexpected error occurred.",
    to_label: "To",
    cc_bcc_btn: "CC / BCC",
    cc_label: "Cc",
    bcc_label: "Bcc",
    importance_label: "Importance",
    importance_low: "Low Importance",
    importance_normal: "Normal",
    importance_high: "High Importance",
    subject_label: "Subject",
    subject_placeholder: "Message subject",
    font_placeholder: "Font",
    size_placeholder: "Size",
    text_color: "Text Color",
    highlight_color: "Highlight Color",
    body_placeholder: "Type your message here...",
    attach_btn: "Attach",
    sig_btn: "Signature",
    no_sig: "No signature",
    manage_sigs_btn: "+ Manage Signatures",
    only_reply: "Only Reply",
    only_forward: "Only Forward",
    send_archive: "Send and Archive",
    send_snooze: "Send and Snooze (Tomorrow)",
    send_move_to: "Send and Move to...",
    send_to_col: "Send to",
    manage_sigs_title: "Manage Signatures",
    saved_sigs: "Saved Signatures",
    create_sig: "Create New Signature",
    sig_name_placeholder: "Name (ex: IPVC, Personal, English...)",
    add_image: "Add Image",
    sig_body_placeholder: "Type your signature here...",
    save_sig_btn: "Save Signature",
    history_from: "From:",
    history_sent: "Sent:",
    history_to: "To:",
    history_cc: "Cc:",
    history_subject: "Subject:",

    // Painel de Filtros
    filter_show: "Show Filters",
    filter_active_single: "active",
    filter_active_plural: "active",
    filter_title: "Search Filters",
    filter_clear: "Clear All",
    filter_search_label: "General Search",
    filter_search_placeholder: "Ex: invoice, report, subject...",
    filter_sender_label: "Sender",
    filter_sender_placeholder: "email@example.com or Name",
    filter_tags_label: "Tags",
    filter_tags_placeholder: "Type and press Enter...",
    filter_tags_suggestions: "Quick suggestions",
    filter_priority_label: "Priority",
    filter_priority_low: "Low",
    filter_priority_medium: "Medium",
    filter_priority_high: "High",
    filter_priority_urgent: "Urgent",
    filter_attachments_label: "Attachments",
    filter_att_all: "All emails",
    filter_att_yes: "Only with attachments",
    filter_att_no: "No attachments",
    filter_read_label: "Read Status",
    filter_read_all: "Read and Unread",
    filter_read_yes: "Read Only",
    filter_read_no: "Unread Only",
    filter_date_label: "Date Range",
    filter_date_to: "to",

    // Colunas Kanban (Grupos de Data e UI)
    group_today: "Today",
    group_yesterday: "Yesterday",
    group_last_week: "Last Week",
    group_last_month: "Last Month",
    group_older: "Older",
    snoozed_single: "Snoozed",
    snoozed_plural: "Snoozed", // Em inglês é igual para singular e plural
    col_all_clear: "All clear!",
    loading_more: "Loading...",
    search_older: "Load older emails",
    searching: "Loading...",
    unread_emails: "unread",

    // Cartão de Thread Kanban
    priority_none: "No Priority",
    priority_low_text: "Low",
    priority_medium_text: "Medium",
    priority_high_text: "High",
    priority_urgent_text: "Urgent",
    snooze_title: "Snooze Email",
    snooze_later_today: "Later Today (In 4h)",
    snooze_tomorrow: "Tomorrow Morning",
    snooze_next_week: "Next Week",
    snooze_custom_date: "Choose Custom Date",
    snooze_confirm: "Confirm",
    snoozed_success: "Email Snoozed",
    snoozed_desc: "The message will reappear on",
    snooze_wake: "Wake Up Now",
    snooze_cancelled: "Snooze Cancelled",
    snooze_cancelled_desc: "The email is active again in the Kanban.",
    snooze_wakes_at: "Wakes at:",
    archive_success: "Conversation Archived",
    archive_desc: "Moved to the Outlook Archive folder.",
    archive_error: "Failed to archive email",
    restore_inbox: "Move to Inbox",
    restore_not_spam: "Not Spam",
    restore_success: "Restored",
    restore_desc: "Conversation moved to Inbox.",
    restore_error: "Failed to restore email",
    spam_success: "Spam",
    spam_desc: "Conversation moved to Junk Email.",
    spam_error: "Failed to mark as Spam",
    spam_mark: "Mark as Spam",
    delete_forever: "Delete Forever",
    delete_normal: "Delete",
    delete_success_forever: "Permanently Deleted",
    delete_desc_forever: "The conversation has been permanently removed.",
    delete_success: "Deleted",
    delete_desc: "Conversation moved to Deleted Items.",
    delete_error_forever: "Failed to permanently delete",
    delete_error: "Failed to delete email",
    delete_modal_title: "Delete Email",
    delete_modal_desc_forever: "This action will permanently delete the conversation. It cannot be recovered.",
    delete_modal_desc: "Are you sure you want to delete this conversation? This will move the emails to the Deleted Items folder.",
    manage_tags_deadlines: "Manage Deadlines and Tags",
    archive_btn: "Archive",
    due_date_label: "Due Date",
    add_tags_label: "Add Tags",
    tag_placeholder: "New tag",
    you_sender: "You",
    msg_count: "msg",
    unread_badge: "unread",

    // Visualizador de Email (Email Viewer)
    error_load_email: "Could not load the full email content.",
    email_read: "Email read",
    email_read_desc: "Successfully marked as read.",
    email_archived: "Email archived",
    email_archived_desc: "The message was moved to the archive.",
    error_archive: "Could not archive the email.",
    email_deleted: "Email deleted",
    email_deleted_desc: "The message was moved to Deleted Items.",
    error_delete: "Could not delete the email.",
    error_attachment: "Error processing attachment",
    error_attachment_desc: "Could not read this file.",
    error_download: "Download Error",
    error_download_desc: "The content of this attachment is not available.",
    tasks_btn: "Tasks",
    to_label_caps: "TO:",
    new_msg_badge: "New Message",
    attachments_title: "Attachments",
    open_attachment: "Open attachment",
    download_attachment: "Download attachment",
    loading_content: "Loading content...",
    reply_btn: "Reply",
    reply_all_btn: "All",
    forward_btn: "Forward",
    task_list: "Task List",
    progress: "Progress",
    of_word: "of",
    no_tasks: "No tasks associated.",
    click_to_add: "Click below to add.",
    task_placeholder: "Describe the task...",
    new_task: "New Task",
    delete_email_desc: "Are you sure you want to delete this message? This action will move the email to the Deleted Items folder.",
    content_unavailable: "Content not available",
    delete_btn: "Delete",
    close_btn: "Close",
    delete_email_title: "Delete Email",

    // Backoffice / Admin
    checking_creds: "Checking credentials...",
    restricted_area: "Restricted Area",
    admin_only: "Only administrators can access this page.",
    back_to_platform: "Back to Platform",
    admin_panel_title: "Administration Panel",
    admin_panel_desc: "Monitoring and metrics for the Kanban platform.",
    exit_btn: "Exit",
    total_users: "Total Users",
    active_7_days: "Active (7 Days)",
    registered_users: "Registered Users",
    search_user_placeholder: "Search user...",
    table_account: "Account & Email",
    table_joined: "Joined",
    table_last_active: "Last Active",
    loading_info: "Loading information...",
    no_user_found: "No user found.",
    online_now: "Online Now",
    offline: "Offline",
  }
};

export type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations["pt"]) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("pt");

  useEffect(() => {
    const savedLang = localStorage.getItem("app_lang") as Language;
    if (savedLang === "pt" || savedLang === "en") {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: keyof typeof translations["pt"]) => {
    return translations[language][key] || translations["pt"][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage deve ser usado dentro de um LanguageProvider");
  }
  return context;
}